### ISSUE TITLE
metadata bounds is exported with two errors

### ISSUE THREAD

**Issue by d2ns** [eito/iOS-GPX-Framework#1]
1)
The export contains only minlat and minlon, the necessary maxlat and maxlon information is missing.

2)
[bounds ...] is followed by [/bounds], which is wrong.
(→ you can create a correct export with garmin basecamp)

The export looks like
[bounds minlat="53.019512" minlon="4.734689"] [/bounds]

but it should look like
[ bounds minlat="53.019512" minlon="4.734689" maxlat="53.046126" maxlon="4.764963"/]
not followed by [/bounds]

**Comment by eito** [comment]
fixed.

**Comment by eito** [comment]
What is the issue with the explicit close 'bounds' tag?

**Comment by eito** [comment]
seems like that is just an optimization, not really incorrect GPX output
