### ISSUE TITLE
Can't get framework file after building

### ISSUE THREAD

**Issue by waterskier2007** [eito/iOS-GPX-Framework#5]
Perhaps I am missing something, but I cannot use the project to generate a GPX.framework file, as one should be able to.

**Comment by eito** [comment]
This project was initiated before real "frameworks" could be built for iOS. So the binary that was produced was a static library. You should see libgpx-static.a in your output directory. 

That being said -- I've updated the GPX project to include a dynamic version as well. You will need to deploy to iOS 8 and up.

**Comment by eito** [comment]
closing as this is now addressed
